### ISSUE TITLE
equity changes preflop

### ISSUE THREAD

**Issue by 506574657220426F656C650D** [alexyz/pokerjs#1]
I really like your calculator. works really smooth.

I found one issue. If we select two hands preflop and we hit calculate multiple times, the equity changes. Any clue why?

**Comment by alexyz** [comment]
Hi Peter

Glad you like the calculator

Preflop equity is estimated because there are too many combinations of 5 cards to test them all. Something like 100 million. In this case it picks 1000 sample boards instead. This will cause slight variations in equity when run multiple times.

When there are no more than two unknown cards it will be able to give an exact answer.

Alex

Sent from my iPhone

On 25 Aug 2017, at 14:29, PeterBoele <notifications@github.com<mailto:notifications@github.com>> wrote:


I really like your calculator. works really smooth.

I found one issue. If we select two hands preflop and we hit calculate multiple times, the equity changes. Any clue why?

**Comment by 506574657220426F656C650D** [comment]
Thanks Alex,

Your comment was very useful. I changed the 1000 sample boards to 70000. Works still almost instant and is more accurate. Thanks again.
